from enum import Enum


class Backgrounds(Enum):
    ACOLYTE = "acolyte"
    ACROBAT = "acrobat"
    ANIMAL_WHISPERER = "animal_whisperer"
    ARTISAN = "artisan"
    ARTIST = "artist"
    BARKEEP = "barkeep"
    BARRISTER = "barrister"
    BOUNTY_HUNTER = "bounty_hunter"
    CHARLATAN = "charlatan"
    CRIMINAL = "criminal"
    DETECTIVE = "detective"
    EMISSARY = "emissary"
    ENTERTAINER = "entertainer"
    FARMHAND = "farmhand"
    FIELD_MEDIC = "field_medic"
    FORTUNE_TELLER = "fortune_teller"
    GAMBLER = "gambler"
    GLADIATOR = "gladiator"
    GUARD = "guard"
    HERBALIST = "herbalist"
    HERMIT = "hermit"
    HUNTER = "hunter"
    LABORER = "laborer"
    MAGICAL_EXPERIMENT = "magical_experiment"
    MARTIAL_DISCIPLE = "martial_disciple"
    MECHANIC = "mechanic"
    MERCHANT = "merchant"
    MINER = "miner"
    NOBLE = "noble"
    NONE = "none"
    NOMAD = "nomad"
    PRISONER = "prisoner"
    SAILOR = "sailor"
    SCHOLAR = "scholar"
    SCOUT = "scout"
    STREET_URCHIN = "street_urchin"
    TINKER = "tinker"
    WARRIOR = "warrior"
