from enum import Enum


class Lores(Enum):
    ACADEMIA = "academia"
    ACCOUNTING = "accounting"
    ARCHITECTURE = "architecture"
    ART = "art"
    CIRCUS = "circus"
    ENGINEERING = "engineering"
    FARMING = "farming"
    FISHING = "fishing"
    FORTUNE_TELLING = "fortune_telling"
    GAMES = "games"
    GENEALOGY = "genealogy"
    GLADIATORIAL = "gladiatorial"
    GUILD = "guild"
    HERALDRY = "heraldry"
    HERBALISM = "herbalism"
    HUNTING = "hunting"
    LABOR = "labor"
    LEGAL = "legal"
    LIBRARY = "library"
    MOUNTAIN = "mountain"
    CAVE = "cave"
    RIVER = "river"
    ALCOHOL = "alcohol"
    BAKING = "baking"
    BUTCHERING = "butchering"
    COOKING = "cooking"
    TEA = "tea"
    MERCANTILE = "mercantile"
    MIDWIFERY = "midwifery"
    MILLING = "milling"
    MINING = "mining"
    SAILING = "sailing"
    SCOUTING = "scouting"
    SCRIBING = "scribing"
    STABLING = "stabling"
    TANNING = "tanning"
    THEATER = "theater"
    UNDERWORLD = "underworld"
    WARFARE = "warfare"
    ELVEN = "elven"
    GOBLIN = "goblin"
    DWARVEN = "dwarven"
